#include "StdAfx.h"
#include "FutureContract_TradeDialogs.h"

ImplementClass(CDailyMacroEnvironmentDlg,CDialogPlaceHolder)

ImplementClass(CDialogDailyTradeSummarize,CDialogPlaceHolder)

ImplementClass(CDialogFutureContract_IntradayTrade,CDialogPlaceHolder)

ImplementClass(CDialogDailyTrades_SingleTradeTrack,CDialogPlaceHolder)

ImplementClass(CDialogFutureContract_LongPeriodicAnalyze,CDialogPlaceHolder)

ImplementClass(CDialogFutureContract_MinorCycleAnalyze,CDialogTabItem_MinorCycleAnalyze)

ImplementClass(CDialogFutureContract_TrackPhraseIn1Day,CCustomTabCtrlDlg)

