#include "StdAfx.h"
#include "FutureContract_TradeDialogs.h"

ImplementClass(CDailyMacroEnvironmentDlg,CDialogPlaceHolderBusiness)

ImplementClass(CDialogDailyTradeSummarize,CDialogPlaceHolderBusiness)

ImplementClass(CDialogFutureContract_IntradayTrade,CDialogPlaceHolderBusiness)

ImplementClass(CDialogDailyTrades_SingleTradeTrack,CDialogPlaceHolderBusiness)

ImplementClass(CDialogFutureContract_MinorCycleAnalyze,CDialogTabItem_MinorCycleAnalyze)


