// XTPDockingPaneResource.h
//
// (c)1998-2023 Codejock Software, All Rights Reserved.
//
// THIS SOURCE FILE IS THE PROPERTY OF CODEJOCK SOFTWARE AND IS NOT TO BE
// RE-DISTRIBUTED BY ANY MEANS WHATSOEVER WITHOUT THE EXPRESSED WRITTEN
// CONSENT OF CODEJOCK SOFTWARE.
//
// THIS SOURCE CODE CAN ONLY BE USED UNDER THE TERMS AND CONDITIONS OUTLINED
// IN THE XTREME TOOLKIT PRO LICENSE AGREEMENT. CODEJOCK SOFTWARE GRANTS TO
// YOU (ONE SOFTWARE DEVELOPER) THE LIMITED RIGHT TO USE THIS SOFTWARE ON A
// SINGLE COMPUTER.
//
// CONTACT INFORMATION:
// support@codejock.com
// http://www.codejock.com
//
/////////////////////////////////////////////////////////////////////////////

#define XTP_DOCKINGPANE_RESOURCE_FIRST 9500
#define XTP_DOCKINGPANE_RESOURCE_LAST 9529

#define XTP_XAML_DOCKINGPANE_STICKERS_VC2005_BACK 9500
#define XTP_XAML_DOCKINGPANE_STICKERS_VC2005_CENTER 9501
#define XTP_XAML_DOCKINGPANE_STICKERS_VC2005_LEFT 9502
#define XTP_XAML_DOCKINGPANE_STICKERS_VC2005_TOP 9503
#define XTP_XAML_DOCKINGPANE_STICKERS_VC2005_RIGHT 9504
#define XTP_XAML_DOCKINGPANE_STICKERS_VC2005_BOTTOM 9505
#define XTP_XAML_DOCKINGPANE_STICKERS_VC2005_CENTER_SELECTED 9506
#define XTP_XAML_DOCKINGPANE_STICKERS_VC2005_LEFT_SELECTED 9507
#define XTP_XAML_DOCKINGPANE_STICKERS_VC2005_TOP_SELECTED 9508
#define XTP_XAML_DOCKINGPANE_STICKERS_VC2005_RIGHT_SELECTED 9509
#define XTP_XAML_DOCKINGPANE_STICKERS_VC2005_BOTTOM_SELECTED 9510
#define XTP_XAML_DOCKINGPANE_STICKERS_VC2008_BACK 9511
#define XTP_XAML_DOCKINGPANE_STICKERS_VC2008_CENTER 9512
#define XTP_XAML_DOCKINGPANE_STICKERS_VC2008_LEFT 9513
#define XTP_XAML_DOCKINGPANE_STICKERS_VC2008_TOP 9514
#define XTP_XAML_DOCKINGPANE_STICKERS_VC2008_RIGHT 9515
#define XTP_XAML_DOCKINGPANE_STICKERS_VC2008_BOTTOM 9516
#define XTP_XAML_DOCKINGPANE_STICKERS_VC2008_CENTER_SELECTED 9517
#define XTP_XAML_DOCKINGPANE_STICKERS_VC2008_LEFT_SELECTED 9518
#define XTP_XAML_DOCKINGPANE_STICKERS_VC2008_TOP_SELECTED 9519
#define XTP_XAML_DOCKINGPANE_STICKERS_VC2008_RIGHT_SELECTED 9520
#define XTP_XAML_DOCKINGPANE_STICKERS_VC2008_BOTTOM_SELECTED 9521

#define XTP_IDS_DOCKINGPANE_AUTOHIDE 9522
#define XTP_IDS_DOCKINGPANE_CLOSE 9523
#define XTP_IDS_DOCKINGPANE_MAXIMIZE 9524
#define XTP_IDS_DOCKINGPANE_RESTORE 9525
#define XTP_IDS_DOCKINGPANE_MENU 9526
#define XTP_IDS_DOCKINGPANE_SELECTWINDOW_ACTIVETOOLS 9527
#define XTP_IDS_DOCKINGPANE_SELECTWINDOW_ACTIVEFILES 9528
