// XTPGridDeprecated.h
//
// (c)1998-2023 Codejock Software, All Rights Reserved.
//
// THIS SOURCE FILE IS THE PROPERTY OF CODEJOCK SOFTWARE AND IS NOT TO BE
// RE-DISTRIBUTED BY ANY MEANS WHATSOEVER WITHOUT THE EXPRESSED WRITTEN
// CONSENT OF CODEJOCK SOFTWARE.
//
// THIS SOURCE CODE CAN ONLY BE USED UNDER THE TERMS AND CONDITIONS OUTLINED
// IN THE XTREME TOOLKIT PRO LICENSE AGREEMENT. CODEJOCK SOFTWARE GRANTS TO
// YOU (ONE SOFTWARE DEVELOPER) THE LIMITED RIGHT TO USE THIS SOFTWARE ON A
// SINGLE COMPUTER.
//
// CONTACT INFORMATION:
// support@codejock.com
// http://www.codejock.com
//
/////////////////////////////////////////////////////////////////////////////

//{{AFX_CODEJOCK_PRIVATE
#if !defined(__XTPGRIDDEPRECATED_H__)
#	define __XTPGRIDDEPRECATED_H__

#	if _MSC_VER > 1000
#		pragma once
#	endif // _MSC_VER > 1000

#	include "Common/Base/Diagnostic/XTPDisableNoisyWarnings.h"

_XTP_DEPRECATED_IN_FAVOR(CXTPGridBehavior)
typedef CXTPGridBehavior CXTReportBehavior;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridBehaviorRow) typedef CXTPGridBehaviorRow CXTReportBehaviorRow;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridBehaviorRowKeyDown)
typedef CXTPGridBehaviorRowKeyDown CXTReportBehaviorRowKeyDown;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridBehaviorRowKeyUp)
typedef CXTPGridBehaviorRowKeyUp CXTReportBehaviorRowKeyUp;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridBehaviorRowModifier)
typedef CXTPGridBehaviorRowModifier CXTReportBehaviorRowModifier;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridBehaviorRowMouse)
typedef CXTPGridBehaviorRowMouse CXTReportBehaviorRowMouse;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridBehaviorRowMouseButton)
typedef CXTPGridBehaviorRowMouseButton CXTReportBehaviorRowMouseButton;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridBorder) typedef CXTPGridBorder CXTReportBorder;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridBorderEdge) typedef CXTPGridBorderEdge CXTReportBorderEdge;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridColumn) typedef CXTPGridColumn CXTReportColumn;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridColumnDisplayOptions)
typedef CXTPGridColumnDisplayOptions CXTReportColumnDisplayOptions;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridColumnDisplaySettings)
typedef CXTPGridColumnDisplaySettings CXTReportColumnDisplaySettings;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridColumnOrder) typedef CXTPGridColumnOrder CXTReportColumnOrder;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridColumns) typedef CXTPGridColumns CXTReportColumns;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridControl) typedef CXTPGridControl CXTReportControl;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridControlLocale)
typedef CXTPGridControlLocale CXTReportControlLocale;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridDataManager) typedef CXTPGridDataManager CXTReportDataManager;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridDataManager) typedef CXTPGridDataManager CXTReportDataManager;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridFilterEditControl)
typedef CXTPGridFilterEditControl CXTReportFilterEditControl;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridGroupRow) typedef CXTPGridGroupRow CXTReportGroupRow;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridHeader) typedef CXTPGridHeader CXTReportHeader;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridHeaderDragWnd)
typedef CXTPGridHeaderDragWnd CXTReportHeaderDragWnd;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridHeaderDropWnd)
typedef CXTPGridHeaderDropWnd CXTReportHeaderDropWnd;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridHitTestInfo) typedef CXTPGridHitTestInfo CXTReportHitTestInfo;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridHyperlink) typedef CXTPGridHyperlink CXTReportHyperlink;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridHyperlinks) typedef CXTPGridHyperlinks CXTReportHyperlinks;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridHyperlinkStyle)
typedef CXTPGridHyperlinkStyle CXTReportHyperlinkStyle;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridIconNavigator)
typedef CXTPGridIconNavigator CXTReportIconNavigator;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridInplaceButton)
typedef CXTPGridInplaceButton CXTReportInplaceButton;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridInplaceButtons)
typedef CXTPGridInplaceButtons CXTReportInplaceButtons;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridInplaceControl)
typedef CXTPGridInplaceControl CXTReportInplaceControl;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridInplaceEdit) typedef CXTPGridInplaceEdit CXTReportInplaceEdit;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridInplaceList) typedef CXTPGridInplaceList CXTReportInplaceList;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridNavigator) typedef CXTPGridNavigator CXTReportNavigator;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridNotifications)
typedef CXTPGridNotifications CXTReportNotifications;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridNotificationsPopulate)
typedef CXTPGridNotificationsPopulate CXTReportNotificationsPopulate;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridNotificationsRow)
typedef CXTPGridNotificationsRow CXTReportNotificationsRow;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridNotificationsSelectedRows)
typedef CXTPGridNotificationsSelectedRows CXTReportNotificationsSelectedRows;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridPageSetupDialog)
typedef CXTPGridPageSetupDialog CXTReportPageSetupDialog;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridPaintManager) typedef CXTPGridPaintManager CXTReportPaintManager;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridRecord) typedef CXTPGridRecord CXTReportRecord;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridRecordItem) typedef CXTPGridRecordItem CXTReportRecordItem;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridRecordItemButton)
typedef CXTPGridRecordItemButton CXTReportRecordItemButton;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridRecordItemConstraint)
typedef CXTPGridRecordItemConstraint CXTReportRecordItemConstraint;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridRecordItemConstraints)
typedef CXTPGridRecordItemConstraints CXTReportRecordItemConstraints;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridRecordItemControl)
typedef CXTPGridRecordItemControl CXTReportRecordItemControl;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridRecordItemControlHookWnd)
typedef CXTPGridRecordItemControlHookWnd CXTReportRecordItemControlHookWnd;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridRecordItemControls)
typedef CXTPGridRecordItemControls CXTReportRecordItemControls;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridRecordItemControls)
typedef CXTPGridRecordItemControls CXTReportRecordItemControls;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridRecordItemDateTime)
typedef CXTPGridRecordItemDateTime CXTReportRecordItemDateTime;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridRecordItemEditOptions)
typedef CXTPGridRecordItemEditOptions CXTReportRecordItemEditOptions;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridRecordItemIcon)
typedef CXTPGridRecordItemIcon CXTReportRecordItemIcon;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridRecordItemId) typedef CXTPGridRecordItemId CXTReportRecordItemId;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridRecordItemNumber)
typedef CXTPGridRecordItemNumber CXTReportRecordItemNumber;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridRecordItemPercentNumber)
typedef CXTPGridRecordItemPercentNumber CXTReportRecordItemPercentNumber;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridRecordItemPreview)
typedef CXTPGridRecordItemPreview CXTReportRecordItemPreview;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridRecordItemRange)
typedef CXTPGridRecordItemRange CXTReportRecordItemRange;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridRecordItemText)
typedef CXTPGridRecordItemText CXTReportRecordItemText;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridRecordItemVariant)
typedef CXTPGridRecordItemVariant CXTReportRecordItemVariant;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridRecordMergeItem)
typedef CXTPGridRecordMergeItem CXTReportRecordMergeItem;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridRecordMergeItemId)
typedef CXTPGridRecordMergeItemId CXTReportRecordMergeItemId;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridRecordMergeItems)
typedef CXTPGridRecordMergeItems CXTReportRecordMergeItems;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridRecords) typedef CXTPGridRecords CXTReportRecords;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridRow) typedef CXTPGridRow CXTReportRow;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridRowBase) typedef CXTPGridRowBase CXTReportRowBase;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridRows) typedef CXTPGridRows CXTReportRows;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridRowsArray) typedef CXTPGridRowsArray CXTReportRowsArray;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridScreenRows) typedef CXTPGridScreenRows CXTReportScreenRows;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridSection) typedef CXTPGridSection CXTReportSection;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridSections) typedef CXTPGridSections CXTReportSections;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridSelectedRows) typedef CXTPGridSelectedRows CXTReportSelectedRows;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridSubListControl)
typedef CXTPGridSubListControl CXTReportSubListControl;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridThemeDefault) typedef CXTPGridThemeDefault CXTReportThemeDefault;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridThemeExplorer)
typedef CXTPGridThemeExplorer CXTReportThemeExplorer;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridThemeNativeWindows10)
typedef CXTPGridThemeNativeWindows10 CXTReportThemeNativeWindows10;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridThemeOffice2003)
typedef CXTPGridThemeOffice2003 CXTReportThemeOffice2003;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridThemeOffice2003Luna)
typedef CXTPGridThemeOffice2003Luna CXTReportThemeOffice2003Luna;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridThemeOffice2013)
typedef CXTPGridThemeOffice2013 CXTReportThemeOffice2013;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridThemeOfficeXP)
typedef CXTPGridThemeOfficeXP CXTReportThemeOfficeXP;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridThemeResource)
typedef CXTPGridThemeResource CXTReportThemeResource;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridThemeVisualStudio2012Blue)
typedef CXTPGridThemeVisualStudio2012Blue CXTReportThemeVisualStudio2012Blue;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridThemeVisualStudio2012Dark)
typedef CXTPGridThemeVisualStudio2012Dark CXTReportThemeVisualStudio2012Dark;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridThemeVisualStudio2012Light)
typedef CXTPGridThemeVisualStudio2012Light CXTReportThemeVisualStudio2012Light;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridThemeVisualStudio2015)
typedef CXTPGridThemeVisualStudio2015 CXTReportThemeVisualStudio2015;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridThemeVisualStudio2017)
typedef CXTPGridThemeVisualStudio2017 CXTReportThemeVisualStudio2017;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridThemeVisualStudio2019)
typedef CXTPGridThemeVisualStudio2019 CXTReportThemeVisualStudio2019;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridThemeVisualStudio2022)
typedef CXTPGridThemeVisualStudio2022 CXTReportThemeVisualStudio2022;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridThickness) typedef CXTPGridThickness CXTReportThickness;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridTip) typedef CXTPGridTip CXTReportTip;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridView) typedef CXTPGridView CXTReportView;
_XTP_DEPRECATED_IN_FAVOR(CXTPGridViewPrintOptions)
typedef CXTPGridViewPrintOptions CXTReportViewPrintOptions;

_XTP_DEPRECATED_IN_FAVOR(XTPGridMouseButton) typedef XTPGridMouseButton XTPReportMouseButton;
_XTP_DEPRECATED_IN_FAVOR(XTPGridMouseEvent) typedef XTPGridMouseEvent XTPReportMouseEvent;
_XTP_DEPRECATED_IN_FAVOR(XTPGridBehavior) typedef XTPGridBehavior XTPReportBehavior;
_XTP_DEPRECATED_IN_FAVOR(XTPGridBorderEdge) typedef XTPGridBorderEdge XTPReportBorderEdge;
_XTP_DEPRECATED_IN_FAVOR(XTPGridColumnBestFitMode)
typedef XTPGridColumnBestFitMode XTPReportColumnBestFitMode;
_XTP_DEPRECATED_IN_FAVOR(XTPGridMouseMode) typedef XTPGridMouseMode XTPReportMouseMode;
_XTP_DEPRECATED_IN_FAVOR(XTPGridDragDrop) typedef XTPGridDragDrop XTPReportDragDrop;
_XTP_DEPRECATED_IN_FAVOR(XTPGridDropMarker) typedef XTPGridDropMarker XTPReportDropMarker;
_XTP_DEPRECATED_IN_FAVOR(XTPGridWatermarkAlignment)
typedef XTPGridWatermarkAlignment XTPReportWatermarkAlignment;
_XTP_DEPRECATED_IN_FAVOR(XTPGridElementRect) typedef XTPGridElementRect XTPReportElementRect;
_XTP_DEPRECATED_IN_FAVOR(XTPGridFilterMode) typedef XTPGridFilterMode XTPReportFilterMode;
_XTP_DEPRECATED_IN_FAVOR(XTPGridScrollUpdateMode)
typedef XTPGridScrollUpdateMode XTPReportScrollUpdateMode;
_XTP_DEPRECATED_IN_FAVOR(XTPGridScrollMode) typedef XTPGridScrollMode XTPReportScrollMode;
_XTP_DEPRECATED_IN_FAVOR(XTPGridShellIcon) typedef XTPGridShellIcon XTPReportShellIcon;
_XTP_DEPRECATED_IN_FAVOR(XTPGridGlyph) typedef XTPGridGlyph XTPReportGlyph;
_XTP_DEPRECATED_IN_FAVOR(XTPGridCheckState) typedef XTPGridCheckState XTPReportCheckState;
_XTP_DEPRECATED_IN_FAVOR(XTPGridRowType) typedef XTPGridRowType XTPReportRowType;
_XTP_DEPRECATED_IN_FAVOR(XTPGridOrientation) typedef XTPGridOrientation XTPReportOrientation;
_XTP_DEPRECATED_IN_FAVOR(XTPGridLineStyle) typedef XTPGridLineStyle XTPReportLineStyle;
_XTP_DEPRECATED_IN_FAVOR(XTPGridFreezeColsDividerStyle)
typedef XTPGridFreezeColsDividerStyle XTPReportFreezeColsDividerStyle;
_XTP_DEPRECATED_IN_FAVOR(XTPGridColumnStyle) typedef XTPGridColumnStyle XTPReportColumnStyle;
_XTP_DEPRECATED_IN_FAVOR(XTPGridTreeStructureStyle)
typedef XTPGridTreeStructureStyle XTPReportTreeStructureStyle;
_XTP_DEPRECATED_IN_FAVOR(XTPGridSectionDividerStyle)
typedef XTPGridSectionDividerStyle XTPReportSectionDividerStyle;
_XTP_DEPRECATED_IN_FAVOR(XTPGridSectionDividerPosition)
typedef XTPGridSectionDividerPosition XTPReportSectionDividerPosition;
_XTP_DEPRECATED_IN_FAVOR(XTPGridDrawSortTriangleStyle)
typedef XTPGridDrawSortTriangleStyle XTPReportDrawSortTriangleStyle;
_XTP_DEPRECATED_IN_FAVOR(XTPGridTextDecoration)
typedef XTPGridTextDecoration XTPReportTextDecoration;
_XTP_DEPRECATED_IN_FAVOR(XTPGridPaintTheme) typedef XTPGridPaintTheme XTPReportPaintTheme;
_XTP_DEPRECATED_IN_FAVOR(XTPGridColumnOrderChangedReason)
typedef XTPGridColumnOrderChangedReason XTPReportColumnOrderChangedReason;
_XTP_DEPRECATED_IN_FAVOR(XTPGridColumnDirection)
typedef XTPGridColumnDirection XTPReportColumnDirection;
_XTP_DEPRECATED_IN_FAVOR(XTPGridHitTestInfoCode)
typedef XTPGridHitTestInfoCode XTPReportHitTestInfoCode;
_XTP_DEPRECATED_IN_FAVOR(XTPGridColumnIconAlignment)
typedef XTPGridColumnIconAlignment XTPReportColumnIconAlignment;
_XTP_DEPRECATED_IN_FAVOR(XTPGridGroupRowIconAlignment)
typedef XTPGridGroupRowIconAlignment XTPReportGroupRowIconAlignment;
_XTP_DEPRECATED_IN_FAVOR(XTPGridVirtualRowFlags)
typedef XTPGridVirtualRowFlags XTPReportVirtualRowFlags;
_XTP_DEPRECATED_IN_FAVOR(XTPGridItemControlType)
typedef XTPGridItemControlType XTPReportItemControlType;
_XTP_DEPRECATED_IN_FAVOR(XTPGridItemControlAlignment)
typedef XTPGridItemControlAlignment XTPReportItemControlAlignment;
_XTP_DEPRECATED_IN_FAVOR(XTPGridTextSearchParms)
typedef XTPGridTextSearchParms XTPReportTextSearchParms;
_XTP_DEPRECATED_IN_FAVOR(XTPGridSelectionChangeType)
typedef XTPGridSelectionChangeType XTPReportSelectionChangeType;
_XTP_DEPRECATED_IN_FAVOR(XTPGridSectionHeightMode)
typedef XTPGridSectionHeightMode XTPReportSectionHeightMode;
_XTP_DEPRECATED_IN_FAVOR(XTPGridSection) typedef XTPGridSection XTPReportSection;

_XTP_DEPRECATED_IN_FAVOR(xtpGridMouseButtonNone)
const XTPGridMouseButton xtpReportMouseButtonNone = xtpGridMouseButtonNone;
_XTP_DEPRECATED_IN_FAVOR(xtpGridMouseButtonLeft)
const XTPGridMouseButton xtpReportMouseButtonLeft = xtpGridMouseButtonLeft;
_XTP_DEPRECATED_IN_FAVOR(xtpGridMouseButtonMiddle)
const XTPGridMouseButton xtpReportMouseButtonMiddle = xtpGridMouseButtonMiddle;
_XTP_DEPRECATED_IN_FAVOR(xtpGridMouseButtonRight)
const XTPGridMouseButton xtpReportMouseButtonRight = xtpGridMouseButtonRight;

_XTP_DEPRECATED_IN_FAVOR(xtpGridMouseEventButtonDown)
const XTPGridMouseEvent xtpReportMouseEventButtonDown = xtpGridMouseEventButtonDown;
_XTP_DEPRECATED_IN_FAVOR(xtpGridMouseEventButtonUp)
const XTPGridMouseEvent xtpReportMouseEventButtonUp = xtpGridMouseEventButtonUp;

_XTP_DEPRECATED_IN_FAVOR(xtpGridBehaviorOutlook2003)
const XTPGridBehavior xtpReportBehaviorOutlook2003 = xtpGridBehaviorOutlook2003;
_XTP_DEPRECATED_IN_FAVOR(xtpGridBehaviorOutlook2007)
const XTPGridBehavior xtpReportBehaviorOutlook2007 = xtpGridBehaviorOutlook2007;
_XTP_DEPRECATED_IN_FAVOR(xtpGridBehaviorOutlook2010)
const XTPGridBehavior xtpReportBehaviorOutlook2010 = xtpGridBehaviorOutlook2010;
_XTP_DEPRECATED_IN_FAVOR(xtpGridBehaviorExcel2003)
const XTPGridBehavior xtpReportBehaviorExcel2003 = xtpGridBehaviorExcel2003;
_XTP_DEPRECATED_IN_FAVOR(xtpGridBehaviorExcel2007)
const XTPGridBehavior xtpReportBehaviorExcel2007 = xtpGridBehaviorExcel2007;
_XTP_DEPRECATED_IN_FAVOR(xtpGridBehaviorExcel2010)
const XTPGridBehavior xtpReportBehaviorExcel2010 = xtpGridBehaviorExcel2010;
_XTP_DEPRECATED_IN_FAVOR(xtpGridBehaviorCodejock1340)
const XTPGridBehavior xtpReportBehaviorCodejock1340 = xtpGridBehaviorCodejock1340;
_XTP_DEPRECATED_IN_FAVOR(xtpGridBehaviorCodejock1341)
const XTPGridBehavior xtpReportBehaviorCodejock1341 = xtpGridBehaviorCodejock1341;
_XTP_DEPRECATED_IN_FAVOR(xtpGridBehaviorCodejock1342)
const XTPGridBehavior xtpReportBehaviorCodejock1342 = xtpGridBehaviorCodejock1342;
_XTP_DEPRECATED_IN_FAVOR(xtpGridBehaviorCodejock1501)
const XTPGridBehavior xtpReportBehaviorCodejock1501 = xtpGridBehaviorCodejock1501;
_XTP_DEPRECATED_IN_FAVOR(xtpGridBehaviorCodejock1502)
const XTPGridBehavior xtpReportBehaviorCodejock1502 = xtpGridBehaviorCodejock1502;
_XTP_DEPRECATED_IN_FAVOR(xtpGridBehaviorCodejockDefault)
const XTPGridBehavior xtpReportBehaviorCodejockDefault = xtpGridBehaviorCodejockDefault;

_XTP_DEPRECATED_IN_FAVOR(xtpGridBorderEdgeLeft)
const XTPGridBorderEdge xtpReportBorderEdgeLeft = xtpGridBorderEdgeLeft;
_XTP_DEPRECATED_IN_FAVOR(xtpGridBorderEdgeTop)
const XTPGridBorderEdge xtpReportBorderEdgeTop = xtpGridBorderEdgeTop;
_XTP_DEPRECATED_IN_FAVOR(xtpGridBorderEdgeRight)
const XTPGridBorderEdge xtpReportBorderEdgeRight = xtpGridBorderEdgeRight;
_XTP_DEPRECATED_IN_FAVOR(xtpGridBorderEdgeBottom)
const XTPGridBorderEdge xtpReportBorderEdgeBottom = xtpGridBorderEdgeBottom;
_XTP_DEPRECATED_IN_FAVOR(xtpGridBorderEdgeCount)
const XTPGridBorderEdge xtpReportBorderEdgeCount = xtpGridBorderEdgeCount;

_XTP_DEPRECATED_IN_FAVOR(xtpGridMouseNothing)
const XTPGridMouseMode xtpReportMouseNothing = xtpGridMouseNothing;
_XTP_DEPRECATED_IN_FAVOR(xtpGridMouseOverColumnDivide)
const XTPGridMouseMode xtpReportMouseOverColumnDivide = xtpGridMouseOverColumnDivide;
_XTP_DEPRECATED_IN_FAVOR(xtpGridMousePrepareDragColumn)
const XTPGridMouseMode xtpReportMousePrepareDragColumn = xtpGridMousePrepareDragColumn;
_XTP_DEPRECATED_IN_FAVOR(xtpGridMouseDraggingColumn)
const XTPGridMouseMode xtpReportMouseDraggingColumn = xtpGridMouseDraggingColumn;
_XTP_DEPRECATED_IN_FAVOR(xtpGridMouseOverRowDivide)
const XTPGridMouseMode xtpReportMouseOverRowDivide = xtpGridMouseOverRowDivide;

_XTP_DEPRECATED_IN_FAVOR(xtpGridAllowDrop)
const XTPGridDragDrop xtpReportAllowDrop = xtpGridAllowDrop;
_XTP_DEPRECATED_IN_FAVOR(xtpGridAllowDragCopy)
const XTPGridDragDrop xtpReportAllowDragCopy = xtpGridAllowDragCopy;
_XTP_DEPRECATED_IN_FAVOR(xtpGridAllowDragMove)
const XTPGridDragDrop xtpReportAllowDragMove = xtpGridAllowDragMove;
_XTP_DEPRECATED_IN_FAVOR(xtpGridAllowDrag)
const XTPGridDragDrop xtpReportAllowDrag = xtpGridAllowDrag;
_XTP_DEPRECATED_IN_FAVOR(xtpGridDontDropAsText)
const XTPGridDragDrop xtpReportDontDropAsText = xtpGridDontDropAsText;

_XTP_DEPRECATED_IN_FAVOR(xtpGridDropBetween)
const XTPGridDropMarker xtpReportDropBetween = xtpGridDropBetween;
_XTP_DEPRECATED_IN_FAVOR(xtpGridDropSelect)
const XTPGridDropMarker xtpReportDropSelect = xtpGridDropSelect;

_XTP_DEPRECATED_IN_FAVOR(xtpGridWatermarkUnknown)
const XTPGridWatermarkAlignment xtpReportWatermarkUnknown = xtpGridWatermarkUnknown;
_XTP_DEPRECATED_IN_FAVOR(xtpGridWatermarkLeft)
const XTPGridWatermarkAlignment xtpReportWatermarkLeft = xtpGridWatermarkLeft;
_XTP_DEPRECATED_IN_FAVOR(xtpGridWatermarkCenter)
const XTPGridWatermarkAlignment xtpReportWatermarkCenter = xtpGridWatermarkCenter;
_XTP_DEPRECATED_IN_FAVOR(xtpGridWatermarkRight)
const XTPGridWatermarkAlignment xtpReportWatermarkRight = xtpGridWatermarkRight;
_XTP_DEPRECATED_IN_FAVOR(xtpGridWatermarkHmask)
const XTPGridWatermarkAlignment xtpReportWatermarkHmask = xtpGridWatermarkHmask;
_XTP_DEPRECATED_IN_FAVOR(xtpGridWatermarkTop)
const XTPGridWatermarkAlignment xtpReportWatermarkTop = xtpGridWatermarkTop;
_XTP_DEPRECATED_IN_FAVOR(xtpGridWatermarkVCenter)
const XTPGridWatermarkAlignment xtpReportWatermarkVCenter = xtpGridWatermarkVCenter;
_XTP_DEPRECATED_IN_FAVOR(xtpGridWatermarkBottom)
const XTPGridWatermarkAlignment xtpReportWatermarkBottom = xtpGridWatermarkBottom;
_XTP_DEPRECATED_IN_FAVOR(xtpGridWatermarkVmask)
const XTPGridWatermarkAlignment xtpReportWatermarkVmask = xtpGridWatermarkVmask;
_XTP_DEPRECATED_IN_FAVOR(xtpGridWatermarkStretch)
const XTPGridWatermarkAlignment xtpReportWatermarkStretch = xtpGridWatermarkStretch;
_XTP_DEPRECATED_IN_FAVOR(xtpGridWatermarkEnlargeOnly)
const XTPGridWatermarkAlignment xtpReportWatermarkEnlargeOnly = xtpGridWatermarkEnlargeOnly;
_XTP_DEPRECATED_IN_FAVOR(xtpGridWatermarkShrinkOnly)
const XTPGridWatermarkAlignment xtpReportWatermarkShrinkOnly = xtpGridWatermarkShrinkOnly;
_XTP_DEPRECATED_IN_FAVOR(xtpGridWatermarkPreserveRatio)
const XTPGridWatermarkAlignment xtpReportWatermarkPreserveRatio = xtpGridWatermarkPreserveRatio;

_XTP_DEPRECATED_IN_FAVOR(xtpGridElementRectGridArea)
const XTPGridElementRect xtpReportElementRectGridArea = xtpGridElementRectGridArea;
_XTP_DEPRECATED_IN_FAVOR(xtpGridElementRectGroupByArea)
const XTPGridElementRect xtpReportElementRectGroupByArea = xtpGridElementRectGroupByArea;
_XTP_DEPRECATED_IN_FAVOR(xtpGridElementRectHeaderArea)
const XTPGridElementRect xtpReportElementRectHeaderArea = xtpGridElementRectHeaderArea;
_XTP_DEPRECATED_IN_FAVOR(xtpGridElementRectFooterArea)
const XTPGridElementRect xtpReportElementRectFooterArea = xtpGridElementRectFooterArea;
_XTP_DEPRECATED_IN_FAVOR(xtpGridElementRectHeaderRecordsArea)
const XTPGridElementRect xtpReportElementRectHeaderRecordsArea = xtpGridElementRectHeaderRecordsArea;
_XTP_DEPRECATED_IN_FAVOR(xtpGridElementRectFooterRecordsArea)
const XTPGridElementRect xtpReportElementRectFooterRecordsArea = xtpGridElementRectFooterRecordsArea;
_XTP_DEPRECATED_IN_FAVOR(xtpGridElementRectHeaderRecordsDividerArea)
const XTPGridElementRect xtpReportElementRectHeaderRecordsDividerArea =
	xtpGridElementRectHeaderRecordsDividerArea;
_XTP_DEPRECATED_IN_FAVOR(xtpGridElementRectFooterRecordsDividerArea)
const XTPGridElementRect xtpReportElementRectFooterRecordsDividerArea =
	xtpGridElementRectFooterRecordsDividerArea;

_XTP_DEPRECATED_IN_FAVOR(xtpGridFilterTreeSimple)
const XTPGridFilterMode xtpReportFilterTreeSimple = xtpGridFilterTreeSimple;
_XTP_DEPRECATED_IN_FAVOR(xtpGridFilterTreeByParentAndChildren)
const XTPGridFilterMode xtpReportFilterTreeByParentAndChildren =
	xtpGridFilterTreeByParentAndChildren;
_XTP_DEPRECATED_IN_FAVOR(xtpGridFilterTreeByEndChildrenOnly)
const XTPGridFilterMode xtpReportFilterTreeByEndChildrenOnly = xtpGridFilterTreeByEndChildrenOnly;

_XTP_DEPRECATED_IN_FAVOR(xtpGridScrollUpdateModeImmediate)
const XTPGridScrollUpdateMode xtpReportScrollUpdateModeImmediate = xtpGridScrollUpdateModeImmediate;
_XTP_DEPRECATED_IN_FAVOR(xtpGridScrollUpdateModeDeferred)
const XTPGridScrollUpdateMode xtpReportScrollUpdateModeDeferred = xtpGridScrollUpdateModeDeferred;

_XTP_DEPRECATED_IN_FAVOR(xtpGridScrollModeNone)
const XTPGridScrollMode xtpReportScrollModeNone = xtpGridScrollModeNone;
_XTP_DEPRECATED_IN_FAVOR(xtpGridScrollModeBlockCount)
const XTPGridScrollMode xtpReportScrollModeBlockCount = xtpGridScrollModeBlockCount;
_XTP_DEPRECATED_IN_FAVOR(xtpGridScrollModeBlockSize)
const XTPGridScrollMode xtpReportScrollModeBlockSize = xtpGridScrollModeBlockSize;
_XTP_DEPRECATED_IN_FAVOR(xtpGridScrollModeSmooth)
const XTPGridScrollMode xtpReportScrollModeSmooth = xtpGridScrollModeSmooth;
_XTP_DEPRECATED_IN_FAVOR(xtpGridScrollModeBlock)
const XTPGridScrollMode xtpReportScrollModeBlock = xtpGridScrollModeBlock;

_XTP_DEPRECATED_IN_FAVOR(xtpGridShellIconLock)
const XTPGridShellIcon xtpReportShellIconLock = xtpGridShellIconLock;

_XTP_DEPRECATED_IN_FAVOR(xtpGridGlyphInvalid)
const XTPGridGlyph xtpReportGlyphInvalid = xtpGridGlyphInvalid;
_XTP_DEPRECATED_IN_FAVOR(xtpGridGlyphRowCollapse)
const XTPGridGlyph xtpReportGlyphRowCollapse = xtpGridGlyphRowCollapse;
_XTP_DEPRECATED_IN_FAVOR(xtpGridGlyphRowExpand)
const XTPGridGlyph xtpReportGlyphRowExpand = xtpGridGlyphRowExpand;
_XTP_DEPRECATED_IN_FAVOR(xtpGridGlyphEnabledUnchecked)
const XTPGridGlyph xtpReportGlyphEnabledUnchecked = xtpGridGlyphEnabledUnchecked;
_XTP_DEPRECATED_IN_FAVOR(xtpGridGlyphEnabledChecked)
const XTPGridGlyph xtpReportGlyphEnabledChecked = xtpGridGlyphEnabledChecked;
_XTP_DEPRECATED_IN_FAVOR(xtpGridGlyphDisabledUnchecked)
const XTPGridGlyph xtpReportGlyphDisabledUnchecked = xtpGridGlyphDisabledUnchecked;
_XTP_DEPRECATED_IN_FAVOR(xtpGridGlyphDisabledChecked)
const XTPGridGlyph xtpReportGlyphDisabledChecked = xtpGridGlyphDisabledChecked;
_XTP_DEPRECATED_IN_FAVOR(xtpGridGlyphColumnExpand)
const XTPGridGlyph xtpReportGlyphColumnExpand = xtpGridGlyphColumnExpand;
_XTP_DEPRECATED_IN_FAVOR(xtpGridGlyphColumnRestore)
const XTPGridGlyph xtpReportGlyphColumnRestore = xtpGridGlyphColumnRestore;
_XTP_DEPRECATED_IN_FAVOR(xtpGridGlyphEnabledTristate)
const XTPGridGlyph xtpReportGlyphEnabledTristate = xtpGridGlyphEnabledTristate;
_XTP_DEPRECATED_IN_FAVOR(xtpGridGlyphItemLocked)
const XTPGridGlyph xtpReportGlyphItemLocked = xtpGridGlyphItemLocked;
_XTP_DEPRECATED_IN_FAVOR(xtpGridGlyphItemUnlocked)
const XTPGridGlyph xtpReportGlyphItemUnlocked = xtpGridGlyphItemUnlocked;
_XTP_DEPRECATED_IN_FAVOR(xtpGridGlyphCount)
const XTPGridGlyph xtpReportGlyphCount = xtpGridGlyphCount;

_XTP_DEPRECATED_IN_FAVOR(xtpGridCheckStateInvalid)
const XTPGridCheckState xtpReportCheckStateInvalid = xtpGridCheckStateInvalid;
_XTP_DEPRECATED_IN_FAVOR(xtpGridCheckStateUnchecked)
const XTPGridCheckState xtpReportCheckStateUnchecked = xtpGridCheckStateUnchecked;
_XTP_DEPRECATED_IN_FAVOR(xtpGridCheckStateChecked)
const XTPGridCheckState xtpReportCheckStateChecked = xtpGridCheckStateChecked;
_XTP_DEPRECATED_IN_FAVOR(xtpGridCheckStateIndeterminate)
const XTPGridCheckState xtpReportCheckStateIndeterminate = xtpGridCheckStateIndeterminate;
_XTP_DEPRECATED_IN_FAVOR(xtpGridCheckStateCount)
const XTPGridCheckState xtpReportCheckStateCount = xtpGridCheckStateCount;

_XTP_DEPRECATED_IN_FAVOR(xtpGridOrientationHorizontal)
const XTPGridOrientation xtpReportOrientationHorizontal = xtpGridOrientationHorizontal;
_XTP_DEPRECATED_IN_FAVOR(xtpGridOrientationVertical)
const XTPGridOrientation xtpReportOrientationVertical = xtpGridOrientationVertical;
_XTP_DEPRECATED_IN_FAVOR(xtpGridOrientationAll)
const XTPGridOrientation xtpReportOrientationAll = xtpGridOrientationAll;

_XTP_DEPRECATED_IN_FAVOR(xtpGridLineStyleNone)
const XTPGridLineStyle xtpReportLineStyleNone = xtpGridLineStyleNone;
_XTP_DEPRECATED_IN_FAVOR(xtpGridLineStyleDotSmall)
const XTPGridLineStyle xtpReportLineStyleDotSmall = xtpGridLineStyleDotSmall;
_XTP_DEPRECATED_IN_FAVOR(xtpGridLineStyleDotLarge)
const XTPGridLineStyle xtpReportLineStyleDotLarge = xtpGridLineStyleDotLarge;
_XTP_DEPRECATED_IN_FAVOR(xtpGridLineStyleDash)
const XTPGridLineStyle xtpReportLineStyleDash = xtpGridLineStyleDash;
_XTP_DEPRECATED_IN_FAVOR(xtpGridLineStyleSolid)
const XTPGridLineStyle xtpReportLineStyleSolid = xtpGridLineStyleSolid;
_XTP_DEPRECATED_IN_FAVOR(xtpGridLineStyleCount)
const XTPGridLineStyle xtpReportLineStyleCount = xtpGridLineStyleCount;
_XTP_DEPRECATED_IN_FAVOR(xtpGridGridNoLines)
const XTPGridLineStyle xtpReportGridNoLines = xtpGridGridNoLines;
_XTP_DEPRECATED_IN_FAVOR(xtpGridGridSmallDots)
const XTPGridLineStyle xtpReportGridSmallDots = xtpGridGridSmallDots;
_XTP_DEPRECATED_IN_FAVOR(xtpGridGridLargeDots)
const XTPGridLineStyle xtpReportGridLargeDots = xtpGridGridLargeDots;
_XTP_DEPRECATED_IN_FAVOR(xtpGridGridDashes)
const XTPGridLineStyle xtpReportGridDashes = xtpGridGridDashes;
_XTP_DEPRECATED_IN_FAVOR(xtpGridGridSolid)
const XTPGridLineStyle xtpReportGridSolid = xtpGridGridSolid;

_XTP_DEPRECATED_IN_FAVOR(xtpGridFreezeColsDividerThin)
const XTPGridFreezeColsDividerStyle xtpReportFreezeColsDividerThin = xtpGridFreezeColsDividerThin;
_XTP_DEPRECATED_IN_FAVOR(xtpGridFreezeColsDividerBold)
const XTPGridFreezeColsDividerStyle xtpReportFreezeColsDividerBold = xtpGridFreezeColsDividerBold;
_XTP_DEPRECATED_IN_FAVOR(xtpGridFreezeColsDividerHeader)
const XTPGridFreezeColsDividerStyle xtpReportFreezeColsDividerHeader =
	xtpGridFreezeColsDividerHeader;
_XTP_DEPRECATED_IN_FAVOR(xtpGridFreezeColsDividerShade)
const XTPGridFreezeColsDividerStyle xtpReportFreezeColsDividerShade = xtpGridFreezeColsDividerShade;
_XTP_DEPRECATED_IN_FAVOR(xtpGridFreezeColsDividerShowAlways)
const XTPGridFreezeColsDividerStyle xtpReportFreezeColsDividerShowAlways =
	xtpGridFreezeColsDividerShowAlways;

_XTP_DEPRECATED_IN_FAVOR(xtpGridColumnShaded)
const XTPGridColumnStyle xtpReportColumnShaded = xtpGridColumnShaded;
_XTP_DEPRECATED_IN_FAVOR(xtpGridColumnFlat)
const XTPGridColumnStyle xtpReportColumnFlat = xtpGridColumnFlat;
_XTP_DEPRECATED_IN_FAVOR(xtpGridColumnExplorer)
const XTPGridColumnStyle xtpReportColumnExplorer = xtpGridColumnExplorer;
_XTP_DEPRECATED_IN_FAVOR(xtpGridColumnOffice2003)
const XTPGridColumnStyle xtpReportColumnOffice2003 = xtpGridColumnOffice2003;
_XTP_DEPRECATED_IN_FAVOR(xtpGridColumnResource)
const XTPGridColumnStyle xtpReportColumnResource = xtpGridColumnResource;

_XTP_DEPRECATED_IN_FAVOR(xtpGridTreeStructureNone)
const XTPGridTreeStructureStyle xtpReportTreeStructureNone = xtpGridTreeStructureNone;
_XTP_DEPRECATED_IN_FAVOR(xtpGridTreeStructureSolid)
const XTPGridTreeStructureStyle xtpReportTreeStructureSolid = xtpGridTreeStructureSolid;
_XTP_DEPRECATED_IN_FAVOR(xtpGridTreeStructureDots)
const XTPGridTreeStructureStyle xtpReportTreeStructureDots = xtpGridTreeStructureDots;

_XTP_DEPRECATED_IN_FAVOR(xtpGridSectionDividerStyleNone)
const XTPGridSectionDividerStyle xtpReportSectionDividerStyleNone = xtpGridSectionDividerStyleNone;
_XTP_DEPRECATED_IN_FAVOR(xtpGridSectionDividerStyleThin)
const XTPGridSectionDividerStyle xtpReportSectionDividerStyleThin = xtpGridSectionDividerStyleThin;
_XTP_DEPRECATED_IN_FAVOR(xtpGridSectionDividerStyleBold)
const XTPGridSectionDividerStyle xtpReportSectionDividerStyleBold = xtpGridSectionDividerStyleBold;
_XTP_DEPRECATED_IN_FAVOR(xtpGridSectionDividerStyleShade)
const XTPGridSectionDividerStyle xtpReportSectionDividerStyleShade = xtpGridSectionDividerStyleShade;
_XTP_DEPRECATED_IN_FAVOR(xtpGridSectionDividerStyleOutlook)
const XTPGridSectionDividerStyle xtpReportSectionDividerStyleOutlook =
	xtpGridSectionDividerStyleOutlook;
_XTP_DEPRECATED_IN_FAVOR(xtpGridFixedRowsDividerNone)
const XTPGridSectionDividerStyle xtpReportFixedRowsDividerNone = xtpGridFixedRowsDividerNone;
_XTP_DEPRECATED_IN_FAVOR(xtpGridFixedRowsDividerThin)
const XTPGridSectionDividerStyle xtpReportFixedRowsDividerThin = xtpGridFixedRowsDividerThin;
_XTP_DEPRECATED_IN_FAVOR(xtpGridFixedRowsDividerBold)
const XTPGridSectionDividerStyle xtpReportFixedRowsDividerBold = xtpGridFixedRowsDividerBold;
_XTP_DEPRECATED_IN_FAVOR(xtpGridFixedRowsDividerShade)
const XTPGridSectionDividerStyle xtpReportFixedRowsDividerShade = xtpGridFixedRowsDividerShade;
_XTP_DEPRECATED_IN_FAVOR(xtpGridFixedRowsDividerOutlook)
const XTPGridSectionDividerStyle xtpReportFixedRowsDividerOutlook = xtpGridFixedRowsDividerOutlook;

_XTP_DEPRECATED_IN_FAVOR(xtpGridSectionDividerPositionTop)
const XTPGridSectionDividerPosition xtpReportSectionDividerPositionTop =
	xtpGridSectionDividerPositionTop;
_XTP_DEPRECATED_IN_FAVOR(xtpGridSectionDividerPositionBottom)
const XTPGridSectionDividerPosition xtpReportSectionDividerPositionBottom =
	xtpGridSectionDividerPositionBottom;

_XTP_DEPRECATED_IN_FAVOR(xtpGridDrawSortTriangleDefault)
const XTPGridDrawSortTriangleStyle xtpReportDrawSortTriangleDefault = xtpGridDrawSortTriangleDefault;
_XTP_DEPRECATED_IN_FAVOR(xtpGridDrawSortTriangleAlways)
const XTPGridDrawSortTriangleStyle xtpReportDrawSortTriangleAlways = xtpGridDrawSortTriangleAlways;
_XTP_DEPRECATED_IN_FAVOR(xtpGridDrawSortTriangleNever)
const XTPGridDrawSortTriangleStyle xtpReportDrawSortTriangleNever = xtpGridDrawSortTriangleNever;

_XTP_DEPRECATED_IN_FAVOR(xtpGridTextDecorationNone)
const XTPGridTextDecoration xtpReportTextDecorationNone = xtpGridTextDecorationNone;
_XTP_DEPRECATED_IN_FAVOR(xtpGridTextDecorationUnderline)
const XTPGridTextDecoration xtpReportTextDecorationUnderline = xtpGridTextDecorationUnderline;

_XTP_DEPRECATED_IN_FAVOR(xtpGridThemeDefault)
const XTPGridPaintTheme xtpReportThemeDefault = xtpGridThemeDefault;
_XTP_DEPRECATED_IN_FAVOR(xtpGridThemeOfficeXP)
const XTPGridPaintTheme xtpReportThemeOfficeXP = xtpGridThemeOfficeXP;
_XTP_DEPRECATED_IN_FAVOR(xtpGridThemeOffice2003)
const XTPGridPaintTheme xtpReportThemeOffice2003 = xtpGridThemeOffice2003;
_XTP_DEPRECATED_IN_FAVOR(xtpGridThemeOffice2003Luna)
const XTPGridPaintTheme xtpReportThemeOffice2003Luna = xtpGridThemeOffice2003Luna;
_XTP_DEPRECATED_IN_FAVOR(xtpGridThemeOffice2013)
const XTPGridPaintTheme xtpReportThemeOffice2013 = xtpGridThemeOffice2013;
_XTP_DEPRECATED_IN_FAVOR(xtpGridThemeOffice2016)
const XTPGridPaintTheme xtpReportThemeOffice2016 = xtpGridThemeOffice2016;
_XTP_DEPRECATED_IN_FAVOR(xtpGridThemeVisualStudio2012Light)
const XTPGridPaintTheme xtpReportThemeVisualStudio2012Light = xtpGridThemeVisualStudio2012Light;
_XTP_DEPRECATED_IN_FAVOR(xtpGridThemeVisualStudio2012Dark)
const XTPGridPaintTheme xtpReportThemeVisualStudio2012Dark = xtpGridThemeVisualStudio2012Dark;
_XTP_DEPRECATED_IN_FAVOR(xtpGridThemeVisualStudio2012Blue)
const XTPGridPaintTheme xtpReportThemeVisualStudio2012Blue = xtpGridThemeVisualStudio2012Blue;
_XTP_DEPRECATED_IN_FAVOR(xtpGridThemeVisualStudio2015)
const XTPGridPaintTheme xtpReportThemeVisualStudio2015 = xtpGridThemeVisualStudio2015;
_XTP_DEPRECATED_IN_FAVOR(xtpGridThemeExplorer)
const XTPGridPaintTheme xtpReportThemeExplorer = xtpGridThemeExplorer;
_XTP_DEPRECATED_IN_FAVOR(xtpGridThemeResource)
const XTPGridPaintTheme xtpReportThemeResource = xtpGridThemeResource;
_XTP_DEPRECATED_IN_FAVOR(xtpGridThemeNativeWindows10)
const XTPGridPaintTheme xtpReportThemeNativeWindows10 = xtpGridThemeNativeWindows10;
_XTP_DEPRECATED_IN_FAVOR(xtpGridThemeVisualStudio2017)
const XTPGridPaintTheme xtpReportThemeVisualStudio2017 = xtpGridThemeVisualStudio2017;
_XTP_DEPRECATED_IN_FAVOR(xtpGridThemeVisualStudio2019)
const XTPGridPaintTheme xtpReportThemeVisualStudio2019 = xtpGridThemeVisualStudio2019;
_XTP_DEPRECATED_IN_FAVOR(xtpGridThemeVisualStudio2022)
const XTPGridPaintTheme xtpReportThemeVisualStudio2022 = xtpGridThemeVisualStudio2022;

_XTP_DEPRECATED_IN_FAVOR(xtpGridColumnChangeOther)
const XTPGridColumnOrderChangedReason xtpReportColumnChangeOther = xtpGridColumnChangeOther;
_XTP_DEPRECATED_IN_FAVOR(xtpGridColumnOrderChanged)
const XTPGridColumnOrderChangedReason xtpReportColumnOrderChanged = xtpGridColumnOrderChanged;
_XTP_DEPRECATED_IN_FAVOR(xtpGridColumnGroupOrderChanged)
const XTPGridColumnOrderChangedReason xtpReportColumnGroupOrderChanged =
	xtpGridColumnGroupOrderChanged;
_XTP_DEPRECATED_IN_FAVOR(xtpGridColumnOrderChangedMask)
const XTPGridColumnOrderChangedReason xtpReportColumnOrderChangedMask =
	xtpGridColumnOrderChangedMask;
_XTP_DEPRECATED_IN_FAVOR(xtpGridColumnAdded)
const XTPGridColumnOrderChangedReason xtpReportColumnAdded = xtpGridColumnAdded;
_XTP_DEPRECATED_IN_FAVOR(xtpGridColumnRemoved)
const XTPGridColumnOrderChangedReason xtpReportColumnRemoved = xtpGridColumnRemoved;
_XTP_DEPRECATED_IN_FAVOR(xtpGridColumnPropExchange)
const XTPGridColumnOrderChangedReason xtpReportColumnPropExchange = xtpGridColumnPropExchange;
_XTP_DEPRECATED_IN_FAVOR(xtpGridColumnCaptionChanged)
const XTPGridColumnOrderChangedReason xtpReportColumnCaptionChanged = xtpGridColumnCaptionChanged;
_XTP_DEPRECATED_IN_FAVOR(xtpGridColumnWidthChanged)
const XTPGridColumnOrderChangedReason xtpReportColumnWidthChanged = xtpGridColumnWidthChanged;
_XTP_DEPRECATED_IN_FAVOR(xtpGridColumnShown)
const XTPGridColumnOrderChangedReason xtpReportColumnShown = xtpGridColumnShown;
_XTP_DEPRECATED_IN_FAVOR(xtpGridColumnHidden)
const XTPGridColumnOrderChangedReason xtpReportColumnHidden = xtpGridColumnHidden;
_XTP_DEPRECATED_IN_FAVOR(xtpGridColumnMoved)
const XTPGridColumnOrderChangedReason xtpReportColumnMoved = xtpGridColumnMoved;
_XTP_DEPRECATED_IN_FAVOR(xtpGridColumnAddedToGroupby)
const XTPGridColumnOrderChangedReason xtpReportColumnAddedToGroupby = xtpGridColumnAddedToGroupby;
_XTP_DEPRECATED_IN_FAVOR(xtpGridColumnRemovedFromGroupby)
const XTPGridColumnOrderChangedReason xtpReportColumnRemovedFromGroupby =
	xtpGridColumnRemovedFromGroupby;
_XTP_DEPRECATED_IN_FAVOR(xtpGridColumnAddedToFieldChooser)
const XTPGridColumnOrderChangedReason xtpReportColumnAddedToFieldChooser =
	xtpGridColumnAddedToFieldChooser;
_XTP_DEPRECATED_IN_FAVOR(xtpGridColumnRemovedFromFieldChooser)
const XTPGridColumnOrderChangedReason xtpReportColumnRemovedFromFieldChooser =
	xtpGridColumnRemovedFromFieldChooser;
_XTP_DEPRECATED_IN_FAVOR(xtpGridColumnChangeMask)
const XTPGridColumnOrderChangedReason xtpReportColumnChangeMask = xtpGridColumnChangeMask;

_XTP_DEPRECATED_IN_FAVOR(xtpGridColumnDirectionLeft)
const XTPGridColumnDirection xtpReportColumnDirectionLeft = xtpGridColumnDirectionLeft;
_XTP_DEPRECATED_IN_FAVOR(xtpGridColumnDirectionRight)
const XTPGridColumnDirection xtpReportColumnDirectionRight = xtpGridColumnDirectionRight;

_XTP_DEPRECATED_IN_FAVOR(xtpGridHitTestUnknown)
const XTPGridHitTestInfoCode xtpReportHitTestUnknown = xtpGridHitTestUnknown;
_XTP_DEPRECATED_IN_FAVOR(xtpGridHitTestHeader)
const XTPGridHitTestInfoCode xtpReportHitTestHeader = xtpGridHitTestHeader;
_XTP_DEPRECATED_IN_FAVOR(xtpGridHitTestGroupBox)
const XTPGridHitTestInfoCode xtpReportHitTestGroupBox = xtpGridHitTestGroupBox;
_XTP_DEPRECATED_IN_FAVOR(xtpGridHitTestBodyRows)
const XTPGridHitTestInfoCode xtpReportHitTestBodyRows = xtpGridHitTestBodyRows;
_XTP_DEPRECATED_IN_FAVOR(xtpGridHitTestBlock)
const XTPGridHitTestInfoCode xtpReportHitTestBlock = xtpGridHitTestBlock;
_XTP_DEPRECATED_IN_FAVOR(xtpGridHitTestHeaderRows)
const XTPGridHitTestInfoCode xtpReportHitTestHeaderRows = xtpGridHitTestHeaderRows;
_XTP_DEPRECATED_IN_FAVOR(xtpGridHitTestFooterRows)
const XTPGridHitTestInfoCode xtpReportHitTestFooterRows = xtpGridHitTestFooterRows;

_XTP_DEPRECATED_IN_FAVOR(xtpGridTextSearchExactPhrase)
const XTPGridTextSearchParms xtpReportTextSearchExactPhrase = xtpGridTextSearchExactPhrase;
_XTP_DEPRECATED_IN_FAVOR(xtpGridTextSearchMatchCase)
const XTPGridTextSearchParms xtpReportTextSearchMatchCase = xtpGridTextSearchMatchCase;
_XTP_DEPRECATED_IN_FAVOR(xtpGridTextSearchBackward)
const XTPGridTextSearchParms xtpReportTextSearchBackward = xtpGridTextSearchBackward;
_XTP_DEPRECATED_IN_FAVOR(xtpGridTextSearchExactStart)
const XTPGridTextSearchParms xtpReportTextSearchExactStart = xtpGridTextSearchExactStart;

_XTP_DEPRECATED_IN_FAVOR(xtpGridSelectionAdd)
const XTPGridSelectionChangeType xtpReportSelectionAdd = xtpGridSelectionAdd;
_XTP_DEPRECATED_IN_FAVOR(xtpGridSelectionRemove)
const XTPGridSelectionChangeType xtpReportSelectionRemove = xtpGridSelectionRemove;
_XTP_DEPRECATED_IN_FAVOR(xtpGridSelectionClear)
const XTPGridSelectionChangeType xtpReportSelectionClear = xtpGridSelectionClear;

_XTP_DEPRECATED_IN_FAVOR(xtpGridSectionHeightModeFixed)
const XTPGridSectionHeightMode xtpReportSectionHeightModeFixed = xtpGridSectionHeightModeFixed;
_XTP_DEPRECATED_IN_FAVOR(xtpGridSectionHeightModeRelative)
const XTPGridSectionHeightMode xtpReportSectionHeightModeRelative = xtpGridSectionHeightModeRelative;
_XTP_DEPRECATED_IN_FAVOR(xtpGridSectionHeightModeAuto)
const XTPGridSectionHeightMode xtpReportSectionHeightModeAuto = xtpGridSectionHeightModeAuto;
_XTP_DEPRECATED_IN_FAVOR(xtpGridSectionHeightModeExpand)
const XTPGridSectionHeightMode xtpReportSectionHeightModeExpand = xtpGridSectionHeightModeExpand;
_XTP_DEPRECATED_IN_FAVOR(xtpGridSectionHeightModeAutoExpand)
const XTPGridSectionHeightMode xtpReportSectionHeightModeAutoExpand =
	xtpGridSectionHeightModeAutoExpand;
_XTP_DEPRECATED_IN_FAVOR(xtpGridSectionHeightModeAutoShrink)
const XTPGridSectionHeightMode xtpReportSectionHeightModeAutoShrink =
	xtpGridSectionHeightModeAutoShrink;

_XTP_DEPRECATED_IN_FAVOR(xtpGridSectionHeader)
const XTPGridSection xtpReportSectionHeader = xtpGridSectionHeader;
_XTP_DEPRECATED_IN_FAVOR(xtpGridSectionBody)
const XTPGridSection xtpReportSectionBody = xtpGridSectionBody;
_XTP_DEPRECATED_IN_FAVOR(xtpGridSectionFooter)
const XTPGridSection xtpReportSectionFooter = xtpGridSectionFooter;
_XTP_DEPRECATED_IN_FAVOR(xtpGridSectionCount)
const XTPGridSection xtpReportSectionCount = xtpGridSectionCount;

_XTP_DEPRECATED_IN_FAVOR(XTP_GRIDRECORDITEM_DRAWARGS)
typedef XTP_GRIDRECORDITEM_DRAWARGS XTP_REPORTRECORDITEM_DRAWARGS;
_XTP_DEPRECATED_IN_FAVOR(XTP_GRIDRECORDITEM_METRICS)
typedef XTP_GRIDRECORDITEM_METRICS XTP_REPORTRECORDITEM_METRICS;
_XTP_DEPRECATED_IN_FAVOR(XTP_GRIDRECORDITEM_ARGS)
typedef XTP_GRIDRECORDITEM_ARGS XTP_REPORTRECORDITEM_ARGS;
_XTP_DEPRECATED_IN_FAVOR(XTP_NM_GRIDTOOLTIPINFO)
typedef XTP_NM_GRIDTOOLTIPINFO XTP_NM_REPORTTOOLTIPINFO;
_XTP_DEPRECATED_IN_FAVOR(XTP_NM_GRIDITEMMETRICS)
typedef XTP_NM_GRIDITEMMETRICS XTP_NM_REPORTITEMMETRICS;
_XTP_DEPRECATED_IN_FAVOR(XTP_NM_GRIDDRAGDROP)
typedef XTP_NM_GRIDDRAGDROP XTP_NM_REPORTDRAGDROP;
_XTP_DEPRECATED_IN_FAVOR(XTP_NM_GRIDPREVIEWKEYDOWN)
typedef XTP_NM_GRIDPREVIEWKEYDOWN XTP_NM_REPORTPREVIEWKEYDOWN;
_XTP_DEPRECATED_IN_FAVOR(XTPGridInputState)
typedef XTPGridInputState XTPReportInputState;
_XTP_DEPRECATED_IN_FAVOR(XTP_GRIDDATAMANAGER_COM_ERROR)
typedef XTP_GRIDDATAMANAGER_COM_ERROR XTP_REPORTDATAMANAGER_COM_ERROR;
_XTP_DEPRECATED_IN_FAVOR(XTP_NM_GRIDSCROLL)
typedef XTP_NM_GRIDSCROLL XTP_NM_REPORTSCROLL;
_XTP_DEPRECATED_IN_FAVOR(XTP_NM_GRIDGIVEFEEDBACK)
typedef XTP_NM_GRIDGIVEFEEDBACK XTP_NM_REPORTGIVEFEEDBACK;
_XTP_DEPRECATED_IN_FAVOR(XTP_NM_GRIDCOLUMNRESIZE)
typedef XTP_NM_GRIDCOLUMNRESIZE XTP_NM_REPORTCOLUMNRESIZE;
_XTP_DEPRECATED_IN_FAVOR(XTP_NM_GRIDROWRESIZE)
typedef XTP_NM_GRIDROWRESIZE XTP_NM_REPORTROWRESIZE;
_XTP_DEPRECATED_IN_FAVOR(XTP_NM_GRIDCOLUMNORDERCHANGED)
typedef XTP_NM_GRIDCOLUMNORDERCHANGED XTP_NM_REPORTCOLUMNORDERCHANGED;
_XTP_DEPRECATED_IN_FAVOR(XTP_GRIDRECORDITEM_CLICKARGS)
typedef XTP_GRIDRECORDITEM_CLICKARGS XTP_REPORTRECORDITEM_CLICKARGS;
_XTP_DEPRECATED_IN_FAVOR(XTP_NM_GRIDRECORDITEM)
typedef XTP_NM_GRIDRECORDITEM XTP_NM_REPORTRECORDITEM;
_XTP_DEPRECATED_IN_FAVOR(XTP_NM_GRIDREQUESTEDIT)
typedef XTP_NM_GRIDREQUESTEDIT XTP_NM_REPORTREQUESTEDIT;
_XTP_DEPRECATED_IN_FAVOR(XTP_NM_GRIDINPLACEBUTTON)
typedef XTP_NM_GRIDINPLACEBUTTON XTP_NM_REPORTINPLACEBUTTON;
_XTP_DEPRECATED_IN_FAVOR(XTP_NM_GRID_BEFORE_COPYPASTE)
typedef XTP_NM_GRID_BEFORE_COPYPASTE XTP_NM_REPORT_BEFORE_COPYPASTE;
_XTP_DEPRECATED_IN_FAVOR(XTP_NM_GRIDCONSTRAINTSELECTING)
typedef XTP_NM_GRIDCONSTRAINTSELECTING XTP_NM_REPORTCONSTRAINTSELECTING;
_XTP_DEPRECATED_IN_FAVOR(XTP_NM_GRIDTOOLTIPINFO)
typedef XTP_NM_GRIDTOOLTIPINFO XTP_NM_REPORTTOOLTIPINFO;
_XTP_DEPRECATED_IN_FAVOR(XTP_GRIDRECORDITEM_METRICS)
typedef XTP_GRIDRECORDITEM_METRICS XTP_REPORTRECORDITEM_METRICS;
_XTP_DEPRECATED_IN_FAVOR(XTP_NM_GRIDITEMCONTROL)
typedef XTP_NM_GRIDITEMCONTROL XTP_NM_REPORTITEMCONTROL;
_XTP_DEPRECATED_IN_FAVOR(XTP_NM_GRIDSTATECHANGED)
typedef XTP_NM_GRIDSTATECHANGED XTP_NM_REPORTSTATECHANGED;

#	ifdef _XTP_ACTIVEX
_XTP_DEPRECATED_IN_FAVOR(XTP_NM_GRIDVALUECHANGING)
typedef XTP_NM_GRIDVALUECHANGING XTP_NM_REPORTVALUECHANGING;
#	endif

namespace XTPREPORTADODB = XTPGRIDADODB;

#	include "Common/Base/Diagnostic/XTPEnableNoisyWarnings.h"
#endif //#if !defined(__XTPGRIDDEPRECATED_H__)
	   //}}AFX_CODEJOCK_PRIVATE