// Exclude.h
//
// (c)1998-2023 Codejock Software, All Rights Reserved.
//
// THIS SOURCE FILE IS THE PROPERTY OF CODEJOCK SOFTWARE AND IS NOT TO BE
// RE-DISTRIBUTED BY ANY MEANS WHATSOEVER WITHOUT THE EXPRESSED WRITTEN
// CONSENT OF CODEJOCK SOFTWARE.
//
// THIS SOURCE CODE CAN ONLY BE USED UNDER THE TERMS AND CONDITIONS OUTLINED
// IN THE XTREME TOOLKIT PRO LICENSE AGREEMENT. CODEJOCK SOFTWARE GRANTS TO
// YOU (ONE SOFTWARE DEVELOPER) THE LIMITED RIGHT TO USE THIS SOFTWARE ON A
// SINGLE COMPUTER.
//
// CONTACT INFORMATION:
// support@codejock.com
// http://www.codejock.com
//
/////////////////////////////////////////////////////////////////////////////

#ifndef _XTP_REQUIRE_MARKUP
#	define _XTP_EXCLUDE_MARKUP
#endif

#ifndef _XTP_REQUIRE_CONTROLS
#	define _XTP_EXCLUDE_CONTROLS
#endif

#ifndef _XTP_REQUIRE_CALENDAR
#	define _XTP_EXCLUDE_CALENDAR
#endif

#ifndef _XTP_REQUIRE_CHART
#	define _XTP_EXCLUDE_CHART
#endif

#ifndef _XTP_REQUIRE_COMMANDBARS
#	define _XTP_EXCLUDE_COMMANDBARS
#endif

#ifndef _XTP_REQUIRE_DOCKINGPANE
#	define _XTP_EXCLUDE_DOCKINGPANE
#endif

#ifndef _XTP_REQUIRE_FLOWGRAPH
#	define _XTP_EXCLUDE_FLOWGRAPH
#endif

#ifndef _XTP_REQUIRE_PROPERTYGRID
#	define _XTP_EXCLUDE_PROPERTYGRID
#endif

#ifndef _XTP_REQUIRE_GRIDCONTROL
#	define _XTP_EXCLUDE_GRIDCONTROL
#endif

#ifndef _XTP_REQUIRE_RIBBON
#	define _XTP_EXCLUDE_RIBBON
#endif

#ifndef _XTP_REQUIRE_SHORTCUTBAR
#	define _XTP_EXCLUDE_SHORTCUTBAR
#endif

#ifndef _XTP_REQUIRE_SKINFRAMEWORK
#	define _XTP_EXCLUDE_SKINFRAMEWORK
#endif

#ifndef _XTP_REQUIRE_SYNTAXEDIT
#	define _XTP_EXCLUDE_SYNTAXEDIT
#endif

#ifndef _XTP_REQUIRE_TASKPANEL
#	define _XTP_EXCLUDE_TASKPANEL
#endif
