// Resource.h : header file
//
// (c)1998-2023 Codejock Software, All Rights Reserved.
//
// THIS SOURCE FILE IS THE PROPERTY OF CODEJOCK SOFTWARE AND IS NOT TO BE
// RE-DISTRIBUTED BY ANY MEANS WHATSOEVER WITHOUT THE EXPRESSED WRITTEN
// CONSENT OF CODEJOCK SOFTWARE.
//
// THIS SOURCE CODE CAN ONLY BE USED UNDER THE TERMS AND CONDITIONS OUTLINED
// IN THE XTREME TOOLKIT PRO LICENSE AGREEMENT. CODEJOCK SOFTWARE GRANTS TO
// YOU (ONE SOFTWARE DEVELOPER) THE LIMITED RIGHT TO USE THIS SOFTWARE ON A
// SINGLE COMPUTER.
//
// CONTACT INFORMATION:
// support@codejock.com
// http://www.codejock.com
//
/////////////////////////////////////////////////////////////////////////////

#define IDD_ABOUTBOX 100
#define IDC_TXT_URL 1000
#define IDC_TXT_EMAIL 1001
#define IDC_TXT_COPYRIGHT 1002
#define IDC_TXT_TITLE 1003
#define IDC_TXT_APPNAME 1004
#define IDC_TXT_CREDITS_INFO 1005
#define IDC_TXT_CREDITS_URL 1006
#define IDC_TXT_CREDITS_WEB 1007
#define IDC_BMP_CODEJOCK 1009
#define IDC_STATIC_BORDER 1010
#define IDC_STATIC_BMP_CODEJOCK 1011

#ifdef XTP_INCLUDE_THEMEDIALOG

#	define IDD_THEME_DIALOG 101
#	define IDC_LIST_THEME 1000
#	define IDC_LIST_COLOR 1001
#	define IDC_LIST_ACCENT 1002
#	define IDC_TXT_COLOR 1003
#	define IDC_TXT_ACCENT 1004
#	define IDC_COMBO_BACK 1005
#	define IDC_TXT_BACK 1006
#	define IDC_CHECK_PREVIEW 1007
#	define IDC_BUTTON_APPLY 1008
#	define IDC_BUTTON_ACCENT 1009

#endif // XTP_INCLUDE_THEMEDIALOG

#define IDI_POPUP_CLOSE 8500
