// RichEditCommands.h : header file
//
// (c)1998-2023 Codejock Software, All Rights Reserved.
//
// THIS SOURCE FILE IS THE PROPERTY OF CODEJOCK SOFTWARE AND IS NOT TO BE
// RE-DISTRIBUTED BY ANY MEANS WHATSOEVER WITHOUT THE EXPRESSED WRITTEN
// CONSENT OF CODEJOCK SOFTWARE.
//
// THIS SOURCE CODE CAN ONLY BE USED UNDER THE TERMS AND CONDITIONS OUTLINED
// IN THE XTREME TOOLKIT PRO LICENSE AGREEMENT. CODEJOCK SOFTWARE GRANTS TO
// YOU (ONE SOFTWARE DEVELOPER) THE LIMITED RIGHT TO USE THIS SOFTWARE ON A
// SINGLE COMPUTER.
//
// CONTACT INFORMATION:
// support@codejock.com
// http://www.codejock.com
//
/////////////////////////////////////////////////////////////////////////////

#define ID_GALLERY_FONTBACKCOLOR 779
#define ID_BACKCOLOR_NOCOLORS 32821

// HOME / Font group
#define ID_GROUP_OPTION_FONT 12010
#define ID_FONT_FACE 12011
#define ID_FONT_FACE_GALLERY 12012
#define ID_FONT_SIZE 12013
#define ID_FONT_SIZE_GALLERY 12014
#define ID_FONT_INCREASE 12015
#define ID_FONT_DECREASE 12016
#define ID_FONT_CHANGECASE 12017
#define ID_FONT_CLEAR 12018
#define ID_FONT_BOLD 12019
#define ID_FONT_ITALIC 12020
#define ID_FONT_UNDERLINE 12021
#define ID_FONT_STRIKETHROUGH 12022
#define ID_FONT_SUBSCRIPT 12023
#define ID_FONT_SUPERSCRIPT 12024
#define ID_FONT_EFFECTS 12025
#define ID_FONT_HIGHLIGHTCOLOR 12026
#define ID_FONT_COLOR 12027
#define ID_FONT_COLOR_GALLERY 12028

// HOME / Paragraph group
#define ID_GROUP_OPTION_PARAGRAPH 12030
#define ID_PARAGRAPH_BULLET 12031
#define ID_PARAGRAPH_NUMBERING 12032
#define ID_PARAGRAPH_LIST 12033
#define ID_PARAGRAPH_DECREASEINDENT 12034
#define ID_PARAGRAPH_INCREASEINDENT 12035
#define ID_PARAGRAPH_SORT 12036
#define ID_PARAGRAPH_SHOWMARKS 12037
#define ID_PARAGRAPH_LEFT 12038
#define ID_PARAGRAPH_CENTER 12039
#define ID_PARAGRAPH_RIGHT 12040
#define ID_PARAGRAPH_JUSTIFY 12041
#define ID_PARAGRAPH_LINESPACING 12042
#define ID_PARAGRAPH_SHADING 12043
#define ID_PARAGRAPH_NOBORDER 12044

// PAGE LAYOUT / Paragraph group
#define ID_PARAGRAPH_INDENT 12280
#define ID_PARAGRAPH_INDENTLEFT 12281
#define ID_PARAGRAPH_INDENTRIGHT 12282
#define ID_PARAGRAPH_SPACING 12283
#define ID_PARAGRAPH_SPACINGBEFORE 12284
#define ID_PARAGRAPH_SPACINGAFTER 12285
